version: '3.7'
services:
  fulstack:
    container_name: fulstack
    build: .
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: npm run start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: